// This file is generated by rust-protobuf 2.18.1. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![rustfmt::skip]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `grpc/health/v1/health.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_18_1;

#[derive(PartialEq,Clone,Default)]
pub struct HealthCheckRequest {
    // message fields
    pub service: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a HealthCheckRequest {
    fn default() -> &'a HealthCheckRequest {
        <HealthCheckRequest as ::protobuf::Message>::default_instance()
    }
}

impl HealthCheckRequest {
    pub fn new() -> HealthCheckRequest {
        ::std::default::Default::default()
    }

    // string service = 1;


    pub fn get_service(&self) -> &str {
        &self.service
    }
    pub fn clear_service(&mut self) {
        self.service.clear();
    }

    // Param is passed by value, moved
    pub fn set_service(&mut self, v: ::std::string::String) {
        self.service = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_service(&mut self) -> &mut ::std::string::String {
        &mut self.service
    }

    // Take field
    pub fn take_service(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.service, ::std::string::String::new())
    }
}

impl ::protobuf::Message for HealthCheckRequest {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.service)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.service.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.service);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.service.is_empty() {
            os.write_string(1, &self.service)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> HealthCheckRequest {
        HealthCheckRequest::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "service",
                |m: &HealthCheckRequest| { &m.service },
                |m: &mut HealthCheckRequest| { &mut m.service },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<HealthCheckRequest>(
                "HealthCheckRequest",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static HealthCheckRequest {
        static instance: ::protobuf::rt::LazyV2<HealthCheckRequest> = ::protobuf::rt::LazyV2::INIT;
        instance.get(HealthCheckRequest::new)
    }
}

impl ::protobuf::Clear for HealthCheckRequest {
    fn clear(&mut self) {
        self.service.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for HealthCheckRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for HealthCheckRequest {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct HealthCheckResponse {
    // message fields
    pub status: ServingStatus,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a HealthCheckResponse {
    fn default() -> &'a HealthCheckResponse {
        <HealthCheckResponse as ::protobuf::Message>::default_instance()
    }
}

impl HealthCheckResponse {
    pub fn new() -> HealthCheckResponse {
        ::std::default::Default::default()
    }

    // .grpc.health.v1.HealthCheckResponse.ServingStatus status = 1;


    pub fn get_status(&self) -> ServingStatus {
        self.status
    }
    pub fn clear_status(&mut self) {
        self.status = ServingStatus::Unknown;
    }

    // Param is passed by value, moved
    pub fn set_status(&mut self, v: ServingStatus) {
        self.status = v;
    }
}

impl ::protobuf::Message for HealthCheckResponse {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type == ::protobuf::wire_format::WireTypeVarint {self.status = is.read_enum()?;} else {return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));}
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.status != ServingStatus::Unknown {
            my_size += ::protobuf::rt::enum_size(1, self.status);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.status != ServingStatus::Unknown {
            os.write_enum(1, ::protobuf::ProtobufEnum::value(&self.status))?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> HealthCheckResponse {
        HealthCheckResponse::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<ServingStatus>>(
                "status",
                |m: &HealthCheckResponse| { &m.status },
                |m: &mut HealthCheckResponse| { &mut m.status },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<HealthCheckResponse>(
                "HealthCheckResponse",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static HealthCheckResponse {
        static instance: ::protobuf::rt::LazyV2<HealthCheckResponse> = ::protobuf::rt::LazyV2::INIT;
        instance.get(HealthCheckResponse::new)
    }
}

impl ::protobuf::Clear for HealthCheckResponse {
    fn clear(&mut self) {
        self.status = ServingStatus::Unknown;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for HealthCheckResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for HealthCheckResponse {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum ServingStatus {
    Unknown = 0,
    Serving = 1,
    NotServing = 2,
    ServiceUnknown = 3,
}

impl ::protobuf::ProtobufEnum for ServingStatus {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<ServingStatus> {
        match value {
            0 => ::std::option::Option::Some(ServingStatus::Unknown),
            1 => ::std::option::Option::Some(ServingStatus::Serving),
            2 => ::std::option::Option::Some(ServingStatus::NotServing),
            3 => ::std::option::Option::Some(ServingStatus::ServiceUnknown),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [ServingStatus] = &[
            ServingStatus::Unknown,
            ServingStatus::Serving,
            ServingStatus::NotServing,
            ServingStatus::ServiceUnknown,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            ::protobuf::reflect::EnumDescriptor::new_pb_name::<ServingStatus>("HealthCheckResponse.ServingStatus", file_descriptor_proto())
        })
    }
}

impl ::std::marker::Copy for ServingStatus {
}

impl ::std::default::Default for ServingStatus {
    fn default() -> Self {
        ServingStatus::Unknown
    }
}

impl ::protobuf::reflect::ProtobufValue for ServingStatus {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Enum(::protobuf::ProtobufEnum::descriptor(self))
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1bgrpc/health/v1/health.proto\x12\x0egrpc.health.v1\".\n\x12HealthCh\
    eckRequest\x12\x18\n\x07service\x18\x01\x20\x01(\tR\x07service\"\xb1\x01\
    \n\x13HealthCheckResponse\x12I\n\x06status\x18\x01\x20\x01(\x0e21.grpc.h\
    ealth.v1.HealthCheckResponse.ServingStatusR\x06status\"O\n\rServingStatu\
    s\x12\x0b\n\x07UNKNOWN\x10\0\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bN\
    OT_SERVING\x10\x02\x12\x13\n\x0fSERVICE_UNKNOWN\x10\x032\xae\x01\n\x06He\
    alth\x12P\n\x05Check\x12\".grpc.health.v1.HealthCheckRequest\x1a#.grpc.h\
    ealth.v1.HealthCheckResponse\x12R\n\x05Watch\x12\".grpc.health.v1.Health\
    CheckRequest\x1a#.grpc.health.v1.HealthCheckResponse0\x01Ba\n\x11io.grpc\
    .health.v1B\x0bHealthProtoP\x01Z,google.golang.org/grpc/health/grpc_heal\
    th_v1\xaa\x02\x0eGrpc.Health.V1J\x97\x12\n\x06\x12\x04\x11\0>\x01\n\xc6\
    \x05\n\x01\x0c\x12\x03\x11\0\x122\xb7\x04\x20Copyright\x202015\x20The\
    \x20gRPC\x20Authors\n\n\x20Licensed\x20under\x20the\x20Apache\x20License\
    ,\x20Version\x202.0\x20(the\x20\"License\");\n\x20you\x20may\x20not\x20u\
    se\x20this\x20file\x20except\x20in\x20compliance\x20with\x20the\x20Licen\
    se.\n\x20You\x20may\x20obtain\x20a\x20copy\x20of\x20the\x20License\x20at\
    \n\n\x20\x20\x20\x20\x20http://www.apache.org/licenses/LICENSE-2.0\n\n\
    \x20Unless\x20required\x20by\x20applicable\x20law\x20or\x20agreed\x20to\
    \x20in\x20writing,\x20software\n\x20distributed\x20under\x20the\x20Licen\
    se\x20is\x20distributed\x20on\x20an\x20\"AS\x20IS\"\x20BASIS,\n\x20WITHO\
    UT\x20WARRANTIES\x20OR\x20CONDITIONS\x20OF\x20ANY\x20KIND,\x20either\x20\
    express\x20or\x20implied.\n\x20See\x20the\x20License\x20for\x20the\x20sp\
    ecific\x20language\x20governing\x20permissions\x20and\n\x20limitations\
    \x20under\x20the\x20License.\n2\x81\x01\x20The\x20canonical\x20version\
    \x20of\x20this\x20proto\x20can\x20be\x20found\x20at\n\x20https://github.\
    com/grpc/grpc-proto/blob/master/grpc/health/v1/health.proto\n\n\x08\n\
    \x01\x02\x12\x03\x13\0\x17\n\x08\n\x01\x08\x12\x03\x15\0+\n\t\n\x02\x08%\
    \x12\x03\x15\0+\n\x08\n\x01\x08\x12\x03\x16\0C\n\t\n\x02\x08\x0b\x12\x03\
    \x16\0C\n\x08\n\x01\x08\x12\x03\x17\0\"\n\t\n\x02\x08\n\x12\x03\x17\0\"\
    \n\x08\n\x01\x08\x12\x03\x18\0,\n\t\n\x02\x08\x08\x12\x03\x18\0,\n\x08\n\
    \x01\x08\x12\x03\x19\0*\n\t\n\x02\x08\x01\x12\x03\x19\0*\n\n\n\x02\x04\0\
    \x12\x04\x1b\0\x1d\x01\n\n\n\x03\x04\0\x01\x12\x03\x1b\x08\x1a\n\x0b\n\
    \x04\x04\0\x02\0\x12\x03\x1c\x02\x15\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\
    \x1c\x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x1c\t\x10\n\x0c\n\x05\
    \x04\0\x02\0\x03\x12\x03\x1c\x13\x14\n\n\n\x02\x04\x01\x12\x04\x1f\0'\
    \x01\n\n\n\x03\x04\x01\x01\x12\x03\x1f\x08\x1b\n\x0c\n\x04\x04\x01\x04\0\
    \x12\x04\x20\x02%\x03\n\x0c\n\x05\x04\x01\x04\0\x01\x12\x03\x20\x07\x14\
    \n\r\n\x06\x04\x01\x04\0\x02\0\x12\x03!\x04\x10\n\x0e\n\x07\x04\x01\x04\
    \0\x02\0\x01\x12\x03!\x04\x0b\n\x0e\n\x07\x04\x01\x04\0\x02\0\x02\x12\
    \x03!\x0e\x0f\n\r\n\x06\x04\x01\x04\0\x02\x01\x12\x03\"\x04\x10\n\x0e\n\
    \x07\x04\x01\x04\0\x02\x01\x01\x12\x03\"\x04\x0b\n\x0e\n\x07\x04\x01\x04\
    \0\x02\x01\x02\x12\x03\"\x0e\x0f\n\r\n\x06\x04\x01\x04\0\x02\x02\x12\x03\
    #\x04\x14\n\x0e\n\x07\x04\x01\x04\0\x02\x02\x01\x12\x03#\x04\x0f\n\x0e\n\
    \x07\x04\x01\x04\0\x02\x02\x02\x12\x03#\x12\x13\n/\n\x06\x04\x01\x04\0\
    \x02\x03\x12\x03$\x04\x18\"\x20\x20Used\x20only\x20by\x20the\x20Watch\
    \x20method.\n\n\x0e\n\x07\x04\x01\x04\0\x02\x03\x01\x12\x03$\x04\x13\n\
    \x0e\n\x07\x04\x01\x04\0\x02\x03\x02\x12\x03$\x16\x17\n\x0b\n\x04\x04\
    \x01\x02\0\x12\x03&\x02\x1b\n\x0c\n\x05\x04\x01\x02\0\x06\x12\x03&\x02\
    \x0f\n\x0c\n\x05\x04\x01\x02\0\x01\x12\x03&\x10\x16\n\x0c\n\x05\x04\x01\
    \x02\0\x03\x12\x03&\x19\x1a\n\n\n\x02\x06\0\x12\x04)\0>\x01\n\n\n\x03\
    \x06\0\x01\x12\x03)\x08\x0e\n^\n\x04\x06\0\x02\0\x12\x03,\x02>\x1aQ\x20I\
    f\x20the\x20requested\x20service\x20is\x20unknown,\x20the\x20call\x20wil\
    l\x20fail\x20with\x20status\n\x20NOT_FOUND.\n\n\x0c\n\x05\x06\0\x02\0\
    \x01\x12\x03,\x06\x0b\n\x0c\n\x05\x06\0\x02\0\x02\x12\x03,\x0c\x1e\n\x0c\
    \n\x05\x06\0\x02\0\x03\x12\x03,)<\n\xde\x06\n\x04\x06\0\x02\x01\x12\x03=\
    \x02E\x1a\xd0\x06\x20Performs\x20a\x20watch\x20for\x20the\x20serving\x20\
    status\x20of\x20the\x20requested\x20service.\n\x20The\x20server\x20will\
    \x20immediately\x20send\x20back\x20a\x20message\x20indicating\x20the\x20\
    current\n\x20serving\x20status.\x20\x20It\x20will\x20then\x20subsequentl\
    y\x20send\x20a\x20new\x20message\x20whenever\n\x20the\x20service's\x20se\
    rving\x20status\x20changes.\n\n\x20If\x20the\x20requested\x20service\x20\
    is\x20unknown\x20when\x20the\x20call\x20is\x20received,\x20the\n\x20serv\
    er\x20will\x20send\x20a\x20message\x20setting\x20the\x20serving\x20statu\
    s\x20to\n\x20SERVICE_UNKNOWN\x20but\x20will\x20*not*\x20terminate\x20the\
    \x20call.\x20\x20If\x20at\x20some\n\x20future\x20point,\x20the\x20servin\
    g\x20status\x20of\x20the\x20service\x20becomes\x20known,\x20the\n\x20ser\
    ver\x20will\x20send\x20a\x20new\x20message\x20with\x20the\x20service's\
    \x20serving\x20status.\n\n\x20If\x20the\x20call\x20terminates\x20with\
    \x20status\x20UNIMPLEMENTED,\x20then\x20clients\n\x20should\x20assume\
    \x20this\x20method\x20is\x20not\x20supported\x20and\x20should\x20not\x20\
    retry\x20the\n\x20call.\x20\x20If\x20the\x20call\x20terminates\x20with\
    \x20any\x20other\x20status\x20(including\x20OK),\n\x20clients\x20should\
    \x20retry\x20the\x20call\x20with\x20appropriate\x20exponential\x20backof\
    f.\n\n\x0c\n\x05\x06\0\x02\x01\x01\x12\x03=\x06\x0b\n\x0c\n\x05\x06\0\
    \x02\x01\x02\x12\x03=\x0c\x1e\n\x0c\n\x05\x06\0\x02\x01\x06\x12\x03=)/\n\
    \x0c\n\x05\x06\0\x02\x01\x03\x12\x03=0Cb\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

#[allow(deprecated)]
fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
pub use super::health_grpc::*;
