// This file is generated by rust-protobuf 2.8.2. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `grpc/testing/stats.proto`

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

/// Generated files are compatible only with the same version
/// of protobuf runtime.

#[derive(PartialEq,Clone,Default)]
pub struct ServerStats {
    // message fields
    pub time_elapsed: f64,
    pub time_user: f64,
    pub time_system: f64,
    pub total_cpu_time: u64,
    pub idle_cpu_time: u64,
    pub cq_poll_count: u64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ServerStats {
    fn default() -> &'a ServerStats {
        <ServerStats as ::protobuf::Message>::default_instance()
    }
}

impl ServerStats {
    pub fn new() -> ServerStats {
        ::std::default::Default::default()
    }

    // double time_elapsed = 1;


    pub fn get_time_elapsed(&self) -> f64 {
        self.time_elapsed
    }
    pub fn clear_time_elapsed(&mut self) {
        self.time_elapsed = 0.;
    }

    // Param is passed by value, moved
    pub fn set_time_elapsed(&mut self, v: f64) {
        self.time_elapsed = v;
    }

    // double time_user = 2;


    pub fn get_time_user(&self) -> f64 {
        self.time_user
    }
    pub fn clear_time_user(&mut self) {
        self.time_user = 0.;
    }

    // Param is passed by value, moved
    pub fn set_time_user(&mut self, v: f64) {
        self.time_user = v;
    }

    // double time_system = 3;


    pub fn get_time_system(&self) -> f64 {
        self.time_system
    }
    pub fn clear_time_system(&mut self) {
        self.time_system = 0.;
    }

    // Param is passed by value, moved
    pub fn set_time_system(&mut self, v: f64) {
        self.time_system = v;
    }

    // uint64 total_cpu_time = 4;


    pub fn get_total_cpu_time(&self) -> u64 {
        self.total_cpu_time
    }
    pub fn clear_total_cpu_time(&mut self) {
        self.total_cpu_time = 0;
    }

    // Param is passed by value, moved
    pub fn set_total_cpu_time(&mut self, v: u64) {
        self.total_cpu_time = v;
    }

    // uint64 idle_cpu_time = 5;


    pub fn get_idle_cpu_time(&self) -> u64 {
        self.idle_cpu_time
    }
    pub fn clear_idle_cpu_time(&mut self) {
        self.idle_cpu_time = 0;
    }

    // Param is passed by value, moved
    pub fn set_idle_cpu_time(&mut self, v: u64) {
        self.idle_cpu_time = v;
    }

    // uint64 cq_poll_count = 6;


    pub fn get_cq_poll_count(&self) -> u64 {
        self.cq_poll_count
    }
    pub fn clear_cq_poll_count(&mut self) {
        self.cq_poll_count = 0;
    }

    // Param is passed by value, moved
    pub fn set_cq_poll_count(&mut self, v: u64) {
        self.cq_poll_count = v;
    }
}

impl ::protobuf::Message for ServerStats {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.time_elapsed = tmp;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.time_user = tmp;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.time_system = tmp;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.total_cpu_time = tmp;
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.idle_cpu_time = tmp;
                },
                6 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.cq_poll_count = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.time_elapsed != 0. {
            my_size += 9;
        }
        if self.time_user != 0. {
            my_size += 9;
        }
        if self.time_system != 0. {
            my_size += 9;
        }
        if self.total_cpu_time != 0 {
            my_size += ::protobuf::rt::value_size(4, self.total_cpu_time, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.idle_cpu_time != 0 {
            my_size += ::protobuf::rt::value_size(5, self.idle_cpu_time, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.cq_poll_count != 0 {
            my_size += ::protobuf::rt::value_size(6, self.cq_poll_count, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.time_elapsed != 0. {
            os.write_double(1, self.time_elapsed)?;
        }
        if self.time_user != 0. {
            os.write_double(2, self.time_user)?;
        }
        if self.time_system != 0. {
            os.write_double(3, self.time_system)?;
        }
        if self.total_cpu_time != 0 {
            os.write_uint64(4, self.total_cpu_time)?;
        }
        if self.idle_cpu_time != 0 {
            os.write_uint64(5, self.idle_cpu_time)?;
        }
        if self.cq_poll_count != 0 {
            os.write_uint64(6, self.cq_poll_count)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ServerStats {
        ServerStats::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "time_elapsed",
                    |m: &ServerStats| { &m.time_elapsed },
                    |m: &mut ServerStats| { &mut m.time_elapsed },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "time_user",
                    |m: &ServerStats| { &m.time_user },
                    |m: &mut ServerStats| { &mut m.time_user },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "time_system",
                    |m: &ServerStats| { &m.time_system },
                    |m: &mut ServerStats| { &mut m.time_system },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "total_cpu_time",
                    |m: &ServerStats| { &m.total_cpu_time },
                    |m: &mut ServerStats| { &mut m.total_cpu_time },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "idle_cpu_time",
                    |m: &ServerStats| { &m.idle_cpu_time },
                    |m: &mut ServerStats| { &mut m.idle_cpu_time },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "cq_poll_count",
                    |m: &ServerStats| { &m.cq_poll_count },
                    |m: &mut ServerStats| { &mut m.cq_poll_count },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ServerStats>(
                    "ServerStats",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ServerStats {
        static mut instance: ::protobuf::lazy::Lazy<ServerStats> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ServerStats,
        };
        unsafe {
            instance.get(ServerStats::new)
        }
    }
}

impl ::protobuf::Clear for ServerStats {
    fn clear(&mut self) {
        self.time_elapsed = 0.;
        self.time_user = 0.;
        self.time_system = 0.;
        self.total_cpu_time = 0;
        self.idle_cpu_time = 0;
        self.cq_poll_count = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ServerStats {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ServerStats {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct HistogramParams {
    // message fields
    pub resolution: f64,
    pub max_possible: f64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a HistogramParams {
    fn default() -> &'a HistogramParams {
        <HistogramParams as ::protobuf::Message>::default_instance()
    }
}

impl HistogramParams {
    pub fn new() -> HistogramParams {
        ::std::default::Default::default()
    }

    // double resolution = 1;


    pub fn get_resolution(&self) -> f64 {
        self.resolution
    }
    pub fn clear_resolution(&mut self) {
        self.resolution = 0.;
    }

    // Param is passed by value, moved
    pub fn set_resolution(&mut self, v: f64) {
        self.resolution = v;
    }

    // double max_possible = 2;


    pub fn get_max_possible(&self) -> f64 {
        self.max_possible
    }
    pub fn clear_max_possible(&mut self) {
        self.max_possible = 0.;
    }

    // Param is passed by value, moved
    pub fn set_max_possible(&mut self, v: f64) {
        self.max_possible = v;
    }
}

impl ::protobuf::Message for HistogramParams {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.resolution = tmp;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.max_possible = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.resolution != 0. {
            my_size += 9;
        }
        if self.max_possible != 0. {
            my_size += 9;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.resolution != 0. {
            os.write_double(1, self.resolution)?;
        }
        if self.max_possible != 0. {
            os.write_double(2, self.max_possible)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> HistogramParams {
        HistogramParams::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "resolution",
                    |m: &HistogramParams| { &m.resolution },
                    |m: &mut HistogramParams| { &mut m.resolution },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "max_possible",
                    |m: &HistogramParams| { &m.max_possible },
                    |m: &mut HistogramParams| { &mut m.max_possible },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<HistogramParams>(
                    "HistogramParams",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static HistogramParams {
        static mut instance: ::protobuf::lazy::Lazy<HistogramParams> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const HistogramParams,
        };
        unsafe {
            instance.get(HistogramParams::new)
        }
    }
}

impl ::protobuf::Clear for HistogramParams {
    fn clear(&mut self) {
        self.resolution = 0.;
        self.max_possible = 0.;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for HistogramParams {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for HistogramParams {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct HistogramData {
    // message fields
    pub bucket: ::std::vec::Vec<u32>,
    pub min_seen: f64,
    pub max_seen: f64,
    pub sum: f64,
    pub sum_of_squares: f64,
    pub count: f64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a HistogramData {
    fn default() -> &'a HistogramData {
        <HistogramData as ::protobuf::Message>::default_instance()
    }
}

impl HistogramData {
    pub fn new() -> HistogramData {
        ::std::default::Default::default()
    }

    // repeated uint32 bucket = 1;


    pub fn get_bucket(&self) -> &[u32] {
        &self.bucket
    }
    pub fn clear_bucket(&mut self) {
        self.bucket.clear();
    }

    // Param is passed by value, moved
    pub fn set_bucket(&mut self, v: ::std::vec::Vec<u32>) {
        self.bucket = v;
    }

    // Mutable pointer to the field.
    pub fn mut_bucket(&mut self) -> &mut ::std::vec::Vec<u32> {
        &mut self.bucket
    }

    // Take field
    pub fn take_bucket(&mut self) -> ::std::vec::Vec<u32> {
        ::std::mem::replace(&mut self.bucket, ::std::vec::Vec::new())
    }

    // double min_seen = 2;


    pub fn get_min_seen(&self) -> f64 {
        self.min_seen
    }
    pub fn clear_min_seen(&mut self) {
        self.min_seen = 0.;
    }

    // Param is passed by value, moved
    pub fn set_min_seen(&mut self, v: f64) {
        self.min_seen = v;
    }

    // double max_seen = 3;


    pub fn get_max_seen(&self) -> f64 {
        self.max_seen
    }
    pub fn clear_max_seen(&mut self) {
        self.max_seen = 0.;
    }

    // Param is passed by value, moved
    pub fn set_max_seen(&mut self, v: f64) {
        self.max_seen = v;
    }

    // double sum = 4;


    pub fn get_sum(&self) -> f64 {
        self.sum
    }
    pub fn clear_sum(&mut self) {
        self.sum = 0.;
    }

    // Param is passed by value, moved
    pub fn set_sum(&mut self, v: f64) {
        self.sum = v;
    }

    // double sum_of_squares = 5;


    pub fn get_sum_of_squares(&self) -> f64 {
        self.sum_of_squares
    }
    pub fn clear_sum_of_squares(&mut self) {
        self.sum_of_squares = 0.;
    }

    // Param is passed by value, moved
    pub fn set_sum_of_squares(&mut self, v: f64) {
        self.sum_of_squares = v;
    }

    // double count = 6;


    pub fn get_count(&self) -> f64 {
        self.count
    }
    pub fn clear_count(&mut self) {
        self.count = 0.;
    }

    // Param is passed by value, moved
    pub fn set_count(&mut self, v: f64) {
        self.count = v;
    }
}

impl ::protobuf::Message for HistogramData {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_uint32_into(wire_type, is, &mut self.bucket)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.min_seen = tmp;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.max_seen = tmp;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.sum = tmp;
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.sum_of_squares = tmp;
                },
                6 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.count = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        for value in &self.bucket {
            my_size += ::protobuf::rt::value_size(1, *value, ::protobuf::wire_format::WireTypeVarint);
        };
        if self.min_seen != 0. {
            my_size += 9;
        }
        if self.max_seen != 0. {
            my_size += 9;
        }
        if self.sum != 0. {
            my_size += 9;
        }
        if self.sum_of_squares != 0. {
            my_size += 9;
        }
        if self.count != 0. {
            my_size += 9;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        for v in &self.bucket {
            os.write_uint32(1, *v)?;
        };
        if self.min_seen != 0. {
            os.write_double(2, self.min_seen)?;
        }
        if self.max_seen != 0. {
            os.write_double(3, self.max_seen)?;
        }
        if self.sum != 0. {
            os.write_double(4, self.sum)?;
        }
        if self.sum_of_squares != 0. {
            os.write_double(5, self.sum_of_squares)?;
        }
        if self.count != 0. {
            os.write_double(6, self.count)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> HistogramData {
        HistogramData::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_vec_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "bucket",
                    |m: &HistogramData| { &m.bucket },
                    |m: &mut HistogramData| { &mut m.bucket },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "min_seen",
                    |m: &HistogramData| { &m.min_seen },
                    |m: &mut HistogramData| { &mut m.min_seen },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "max_seen",
                    |m: &HistogramData| { &m.max_seen },
                    |m: &mut HistogramData| { &mut m.max_seen },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "sum",
                    |m: &HistogramData| { &m.sum },
                    |m: &mut HistogramData| { &mut m.sum },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "sum_of_squares",
                    |m: &HistogramData| { &m.sum_of_squares },
                    |m: &mut HistogramData| { &mut m.sum_of_squares },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "count",
                    |m: &HistogramData| { &m.count },
                    |m: &mut HistogramData| { &mut m.count },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<HistogramData>(
                    "HistogramData",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static HistogramData {
        static mut instance: ::protobuf::lazy::Lazy<HistogramData> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const HistogramData,
        };
        unsafe {
            instance.get(HistogramData::new)
        }
    }
}

impl ::protobuf::Clear for HistogramData {
    fn clear(&mut self) {
        self.bucket.clear();
        self.min_seen = 0.;
        self.max_seen = 0.;
        self.sum = 0.;
        self.sum_of_squares = 0.;
        self.count = 0.;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for HistogramData {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for HistogramData {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct RequestResultCount {
    // message fields
    pub status_code: i32,
    pub count: i64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a RequestResultCount {
    fn default() -> &'a RequestResultCount {
        <RequestResultCount as ::protobuf::Message>::default_instance()
    }
}

impl RequestResultCount {
    pub fn new() -> RequestResultCount {
        ::std::default::Default::default()
    }

    // int32 status_code = 1;


    pub fn get_status_code(&self) -> i32 {
        self.status_code
    }
    pub fn clear_status_code(&mut self) {
        self.status_code = 0;
    }

    // Param is passed by value, moved
    pub fn set_status_code(&mut self, v: i32) {
        self.status_code = v;
    }

    // int64 count = 2;


    pub fn get_count(&self) -> i64 {
        self.count
    }
    pub fn clear_count(&mut self) {
        self.count = 0;
    }

    // Param is passed by value, moved
    pub fn set_count(&mut self, v: i64) {
        self.count = v;
    }
}

impl ::protobuf::Message for RequestResultCount {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.status_code = tmp;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.count = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.status_code != 0 {
            my_size += ::protobuf::rt::value_size(1, self.status_code, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.count != 0 {
            my_size += ::protobuf::rt::value_size(2, self.count, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.status_code != 0 {
            os.write_int32(1, self.status_code)?;
        }
        if self.count != 0 {
            os.write_int64(2, self.count)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> RequestResultCount {
        RequestResultCount::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                    "status_code",
                    |m: &RequestResultCount| { &m.status_code },
                    |m: &mut RequestResultCount| { &mut m.status_code },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "count",
                    |m: &RequestResultCount| { &m.count },
                    |m: &mut RequestResultCount| { &mut m.count },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<RequestResultCount>(
                    "RequestResultCount",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static RequestResultCount {
        static mut instance: ::protobuf::lazy::Lazy<RequestResultCount> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const RequestResultCount,
        };
        unsafe {
            instance.get(RequestResultCount::new)
        }
    }
}

impl ::protobuf::Clear for RequestResultCount {
    fn clear(&mut self) {
        self.status_code = 0;
        self.count = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for RequestResultCount {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RequestResultCount {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ClientStats {
    // message fields
    pub latencies: ::protobuf::SingularPtrField<HistogramData>,
    pub time_elapsed: f64,
    pub time_user: f64,
    pub time_system: f64,
    pub request_results: ::protobuf::RepeatedField<RequestResultCount>,
    pub cq_poll_count: u64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ClientStats {
    fn default() -> &'a ClientStats {
        <ClientStats as ::protobuf::Message>::default_instance()
    }
}

impl ClientStats {
    pub fn new() -> ClientStats {
        ::std::default::Default::default()
    }

    // .grpc.testing.HistogramData latencies = 1;


    pub fn get_latencies(&self) -> &HistogramData {
        self.latencies.as_ref().unwrap_or_else(|| HistogramData::default_instance())
    }
    pub fn clear_latencies(&mut self) {
        self.latencies.clear();
    }

    pub fn has_latencies(&self) -> bool {
        self.latencies.is_some()
    }

    // Param is passed by value, moved
    pub fn set_latencies(&mut self, v: HistogramData) {
        self.latencies = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_latencies(&mut self) -> &mut HistogramData {
        if self.latencies.is_none() {
            self.latencies.set_default();
        }
        self.latencies.as_mut().unwrap()
    }

    // Take field
    pub fn take_latencies(&mut self) -> HistogramData {
        self.latencies.take().unwrap_or_else(|| HistogramData::new())
    }

    // double time_elapsed = 2;


    pub fn get_time_elapsed(&self) -> f64 {
        self.time_elapsed
    }
    pub fn clear_time_elapsed(&mut self) {
        self.time_elapsed = 0.;
    }

    // Param is passed by value, moved
    pub fn set_time_elapsed(&mut self, v: f64) {
        self.time_elapsed = v;
    }

    // double time_user = 3;


    pub fn get_time_user(&self) -> f64 {
        self.time_user
    }
    pub fn clear_time_user(&mut self) {
        self.time_user = 0.;
    }

    // Param is passed by value, moved
    pub fn set_time_user(&mut self, v: f64) {
        self.time_user = v;
    }

    // double time_system = 4;


    pub fn get_time_system(&self) -> f64 {
        self.time_system
    }
    pub fn clear_time_system(&mut self) {
        self.time_system = 0.;
    }

    // Param is passed by value, moved
    pub fn set_time_system(&mut self, v: f64) {
        self.time_system = v;
    }

    // repeated .grpc.testing.RequestResultCount request_results = 5;


    pub fn get_request_results(&self) -> &[RequestResultCount] {
        &self.request_results
    }
    pub fn clear_request_results(&mut self) {
        self.request_results.clear();
    }

    // Param is passed by value, moved
    pub fn set_request_results(&mut self, v: ::protobuf::RepeatedField<RequestResultCount>) {
        self.request_results = v;
    }

    // Mutable pointer to the field.
    pub fn mut_request_results(&mut self) -> &mut ::protobuf::RepeatedField<RequestResultCount> {
        &mut self.request_results
    }

    // Take field
    pub fn take_request_results(&mut self) -> ::protobuf::RepeatedField<RequestResultCount> {
        ::std::mem::replace(&mut self.request_results, ::protobuf::RepeatedField::new())
    }

    // uint64 cq_poll_count = 6;


    pub fn get_cq_poll_count(&self) -> u64 {
        self.cq_poll_count
    }
    pub fn clear_cq_poll_count(&mut self) {
        self.cq_poll_count = 0;
    }

    // Param is passed by value, moved
    pub fn set_cq_poll_count(&mut self, v: u64) {
        self.cq_poll_count = v;
    }
}

impl ::protobuf::Message for ClientStats {
    fn is_initialized(&self) -> bool {
        for v in &self.latencies {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.request_results {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.latencies)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.time_elapsed = tmp;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.time_user = tmp;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.time_system = tmp;
                },
                5 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.request_results)?;
                },
                6 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.cq_poll_count = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.latencies.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if self.time_elapsed != 0. {
            my_size += 9;
        }
        if self.time_user != 0. {
            my_size += 9;
        }
        if self.time_system != 0. {
            my_size += 9;
        }
        for value in &self.request_results {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        if self.cq_poll_count != 0 {
            my_size += ::protobuf::rt::value_size(6, self.cq_poll_count, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.latencies.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if self.time_elapsed != 0. {
            os.write_double(2, self.time_elapsed)?;
        }
        if self.time_user != 0. {
            os.write_double(3, self.time_user)?;
        }
        if self.time_system != 0. {
            os.write_double(4, self.time_system)?;
        }
        for v in &self.request_results {
            os.write_tag(5, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        if self.cq_poll_count != 0 {
            os.write_uint64(6, self.cq_poll_count)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ClientStats {
        ClientStats::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<HistogramData>>(
                    "latencies",
                    |m: &ClientStats| { &m.latencies },
                    |m: &mut ClientStats| { &mut m.latencies },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "time_elapsed",
                    |m: &ClientStats| { &m.time_elapsed },
                    |m: &mut ClientStats| { &mut m.time_elapsed },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "time_user",
                    |m: &ClientStats| { &m.time_user },
                    |m: &mut ClientStats| { &mut m.time_user },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "time_system",
                    |m: &ClientStats| { &m.time_system },
                    |m: &mut ClientStats| { &mut m.time_system },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<RequestResultCount>>(
                    "request_results",
                    |m: &ClientStats| { &m.request_results },
                    |m: &mut ClientStats| { &mut m.request_results },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "cq_poll_count",
                    |m: &ClientStats| { &m.cq_poll_count },
                    |m: &mut ClientStats| { &mut m.cq_poll_count },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ClientStats>(
                    "ClientStats",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ClientStats {
        static mut instance: ::protobuf::lazy::Lazy<ClientStats> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ClientStats,
        };
        unsafe {
            instance.get(ClientStats::new)
        }
    }
}

impl ::protobuf::Clear for ClientStats {
    fn clear(&mut self) {
        self.latencies.clear();
        self.time_elapsed = 0.;
        self.time_user = 0.;
        self.time_system = 0.;
        self.request_results.clear();
        self.cq_poll_count = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ClientStats {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ClientStats {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x18grpc/testing/stats.proto\x12\x0cgrpc.testing\"\xdc\x01\n\x0bServer\
    Stats\x12!\n\x0ctime_elapsed\x18\x01\x20\x01(\x01R\x0btimeElapsed\x12\
    \x1b\n\ttime_user\x18\x02\x20\x01(\x01R\x08timeUser\x12\x1f\n\x0btime_sy\
    stem\x18\x03\x20\x01(\x01R\ntimeSystem\x12$\n\x0etotal_cpu_time\x18\x04\
    \x20\x01(\x04R\x0ctotalCpuTime\x12\"\n\ridle_cpu_time\x18\x05\x20\x01(\
    \x04R\x0bidleCpuTime\x12\"\n\rcq_poll_count\x18\x06\x20\x01(\x04R\x0bcqP\
    ollCount\"T\n\x0fHistogramParams\x12\x1e\n\nresolution\x18\x01\x20\x01(\
    \x01R\nresolution\x12!\n\x0cmax_possible\x18\x02\x20\x01(\x01R\x0bmaxPos\
    sible\"\xab\x01\n\rHistogramData\x12\x16\n\x06bucket\x18\x01\x20\x03(\rR\
    \x06bucket\x12\x19\n\x08min_seen\x18\x02\x20\x01(\x01R\x07minSeen\x12\
    \x19\n\x08max_seen\x18\x03\x20\x01(\x01R\x07maxSeen\x12\x10\n\x03sum\x18\
    \x04\x20\x01(\x01R\x03sum\x12$\n\x0esum_of_squares\x18\x05\x20\x01(\x01R\
    \x0csumOfSquares\x12\x14\n\x05count\x18\x06\x20\x01(\x01R\x05count\"K\n\
    \x12RequestResultCount\x12\x1f\n\x0bstatus_code\x18\x01\x20\x01(\x05R\ns\
    tatusCode\x12\x14\n\x05count\x18\x02\x20\x01(\x03R\x05count\"\x98\x02\n\
    \x0bClientStats\x129\n\tlatencies\x18\x01\x20\x01(\x0b2\x1b.grpc.testing\
    .HistogramDataR\tlatencies\x12!\n\x0ctime_elapsed\x18\x02\x20\x01(\x01R\
    \x0btimeElapsed\x12\x1b\n\ttime_user\x18\x03\x20\x01(\x01R\x08timeUser\
    \x12\x1f\n\x0btime_system\x18\x04\x20\x01(\x01R\ntimeSystem\x12I\n\x0fre\
    quest_results\x18\x05\x20\x03(\x0b2\x20.grpc.testing.RequestResultCountR\
    \x0erequestResults\x12\"\n\rcq_poll_count\x18\x06\x20\x01(\x04R\x0bcqPol\
    lCountb\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
